# Setting test expectation screenshots for Playwright
name: Update Playwright Expectations

on:
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    if: >
      ( github.event_name == 'pull_request' && github.event.label.name == 'New Browser Test Expectations' ) ||
      ( github.event.issue.pull_request &&
        github.event_name == 'issue_comment' &&
        (
          github.event.comment.author_association == 'OWNER' ||
          github.event.comment.author_association == 'MEMBER' ||
          github.event.comment.author_association == 'COLLABORATOR'
        ) &&
        startsWith(github.event.comment.body, '/update-playwright') )
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
      pr-number: ${{ steps.pr-info.outputs.pr-number }}
      branch: ${{ steps.pr-info.outputs.branch }}
    steps:
      - name: Get PR info
        id: pr-info
        run: |
          echo "pr-number=${{ github.event.number || github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "branch=$(gh pr view ${{ github.event.number || github.event.issue.number }} --repo ${{ github.repository }} --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.pr-info.outputs.branch }}

      # Setup Test Environment, build frontend but do not start server yet
      - name: Setup ComfyUI server
        uses: ./.github/actions/setup-comfyui-server
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          include_build_step: true
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      # Save the entire workspace as cache for update job to restore
      - name: Generate cache key
        id: cache-key
        run: echo "key=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Save cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: .
          key: comfyui-update-snapshots-${{ steps.cache-key.outputs.key }}

  update-snapshots:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # Restore built frontend repo from setup job
      - name: Wait for cache propagation
        run: sleep 10
      - name: Restore cached setup
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          fail-on-cache-miss: true
          path: .
          key: comfyui-update-snapshots-${{ needs.setup.outputs.cache-key }}

      # Setup Test Environment for this runner, start server, use cached built frontend
      - name: Setup ComfyUI server
        uses: ./.github/actions/setup-comfyui-server
        with:
          launch_server: true
      - name: Setup nodejs, pnpm, reuse built frontend
        uses: ./.github/actions/setup-frontend
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Find Update Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: "find-update-comment"
        with:
          issue-number: ${{ needs.setup.outputs.pr-number }}
          comment-author: "github-actions[bot]"
          body-includes: "Updating Playwright Expectations"

      - name: Add Starting Reaction
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          comment-id: ${{ steps.find-update-comment.outputs.comment-id }}
          issue-number: ${{ needs.setup.outputs.pr-number }}
          body: |
            Updating Playwright Expectations
          edit-mode: replace
          reactions: eyes
      - name: Run Playwright tests and update snapshots (screenshot tests only)
        id: playwright-tests
        run: pnpm exec playwright test --update-snapshots --grep "toHaveScreenshot"
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
      - name: Debugging info
        run: |
          echo "PR: ${{ needs.setup.outputs.pr-number }}"
          echo "Branch: ${{ needs.setup.outputs.branch }}"
          git status
      - name: Commit updated expectations
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add browser_tests
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "[automated] Update test expectations"
            git push origin ${{ needs.setup.outputs.branch }}
          fi

      - name: Add Done Reaction
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        if: github.event_name == 'issue_comment'
        with:
          comment-id: ${{ steps.find-update-comment.outputs.comment-id }}
          issue-number: ${{ needs.setup.outputs.pr-number }}
          reactions: +1
          reactions-edit-mode: replace

      - name: Remove New Browser Test Expectations label
        if: always() && github.event_name == 'pull_request'
        run: gh pr edit ${{ needs.setup.outputs.pr-number }} --remove-label "New Browser Test Expectations"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
